pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Provision Jenkins Job') {
            steps {
                script {
                    def dslScriptPath = 'jenkins/dls/ansible-zabbix-dsl.groovy'
                    echo "File Content: ${fileContent}"

                    jobDsl(scriptText: readFileFromWorkspace(dslScriptPath))
                }
            }
        }
    }
}
